### ISSUE TITLE
PDF does not upload to the bucket.

### ISSUE THREAD

**Issue by augustov58** [Elliott-Chong/chatpdf-yt#26]
HI Elliot. I have issues uploading the PDF file to the bucket. I am in the part of the video https://youtu.be/r895rFUbGtE?t=4635.

I noticed you updated the `S3.ts` file to the AWS sdk-v3 in the repo. I updated mine accordingly but when I try to upload the file I get this and not get any error. 
![image](https://github.com/Elliott-Chong/chatpdf-yt/assets/67004271/59c32933-8e5e-4c73-b6a4-b78310f98066)

But when I try to check the bucket file is not uploaded for some reason. I am using WSL on Windows. Appreciate the help.

**Comment by Ealanisln** [comment]
Have you tried with the code from the last Fileupload component code? 

https://github.com/Elliott-Chong/chatpdf-yt/blob/main/src/components/FileUpload.tsx

Issue relateed:
https://github.com/aws/aws-sdk-js-v3/issues/4126

**Comment by augustov58** [comment]
Yes I tried but apparently was an authentication issue with `process.env.` variables. I managed to solved by adding an error handling in `s3.putObject` Function like this and identified the problem. 

```
s3.putObject(params, (err, data) => {
  if (err) {
    console.error('Upload error:', err);
    return reject(err);
  }
  return resolve({
    file_key,
    file_name: file.name,
  });
});
```

Thank you!
